# Generated by Django 4.0.4 on 2022-05-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_group_teacher_alter_students_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
