# Generated by Django 4.0.4 on 2022-07-20 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.PositiveIntegerField(default=800700600),
        ),
    ]
