# Generated by Django 4.0.4 on 2022-07-28 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_teacher_birth_date_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=64, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='enroll_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='student',
            name='graduate_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 28, 17, 42, 40, 331675)),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
