# Generated by Django 4.0.4 on 2022-07-28 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_email_student_enroll_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduate_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 28, 17, 57, 55, 955864)),
        ),
    ]
