# Generated by Django 4.0.4 on 2022-07-28 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_graduate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduate_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 28, 17, 58, 10, 630413)),
        ),
    ]
