# Generated by Django 4.0.4 on 2022-07-30 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_graduate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduate_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 30, 12, 57, 44, 546068)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.PositiveIntegerField(default='+38(063)000-1111'),
        ),
    ]
