# Generated by Django 4.0.4 on 2022-08-02 09:41

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default=64, max_length=254, validators=[core.validators.validate_email_for_prohibited_domain]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[core.validators.validate_phone]),
        ),
    ]
