# Generated by Django 4.0.4 on 2022-08-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_delete_teacher_alter_student_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
