# Generated by Django 4.0.4 on 2022-08-11 13:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='+38(000)000-000', max_length=20, validators=[core.validators.validate_phone]),
        ),
    ]
