# Generated by Django 4.0.4 on 2022-08-09 12:04

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default=64, max_length=254, validators=[core.validators.validate_email_for_prohibited_domain]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='+38(000)000-000', max_length=20, validators=[core.validators.validate_phone]),
        ),
    ]
