# Generated by Django 4.0.4 on 2022-08-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='UKR00', max_length=5)),
                ('name', models.CharField(default='Course', max_length=30)),
                ('duration', models.DurationField(null=True)),
            ],
        ),
    ]
