# Generated by Django 4.0.4 on 2022-08-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_email_alter_teacher_phone_number'),
        ('courses', '0002_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher_courses', to='teachers.teacher'),
        ),
    ]
