# Generated by Django 4.0.4 on 2022-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_group_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=722)),
                ('class_groups', models.ManyToManyField(related_name='group_classes', to='groups.group')),
            ],
        ),
    ]
